import { listUtilities, listGroups } from "@bearbones/vite";

/**
 * Generate the contents of `node_modules/.bearbones/types.d.ts` (or wherever
 * the host project routes the codegen output).
 *
 * MVP scope:
 *   - `BearbonesUtilityName` — closed union of every utility name shipped by
 *     the preset's static utility map. Generated from `listUtilities()`.
 *   - `BearbonesGroupConditionKey` — union of every dynamically registered
 *     group condition name. Grows as `group()` declarations are discovered.
 *   - `BearbonesConditionKey` — superset of static + dynamic conditions.
 *   - Function signatures for `css`, `cva`, `sva`, `group`, `cx`.
 *
 * Future work tracked in the design spec:
 *   - Generate the input-shape unions from the resolved Panda config so the
 *     condition list reflects the true preset vocabulary, not a hard-coded
 *     mirror.
 *   - Emit source-mapped declarations.
 */

export interface GenerateTypesOptions {
  /**
   * Header banner inserted at the top of the generated file. Override for
   * versioning or to embed a config-content hash.
   */
  banner?: string;
}

const STATIC_CONDITION_KEYS = [
  "_hover",
  "_focus",
  "_focusVisible",
  "_active",
  "_disabled",
  "_checked",
  "_selected",
  "_invalid",
  "_valid",
  "_required",
  "_readOnly",
  "_first",
  "_last",
  "_odd",
  "_even",
  "_empty",
  "_before",
  "_after",
  "_placeholder",
  "_marker",
  "_selection",
  "_dark",
  "_light",
  "_sm",
  "_md",
  "_lg",
  "_xl",
  "_2xl",
] as const;

export function generateTypes(options: GenerateTypesOptions = {}): string {
  const utilities = listUtilities();
  const groups = listGroups();

  const utilityUnion =
    utilities.length === 0 ? "never" : utilities.map((u) => JSON.stringify(u)).join(" | ");

  const groupConditionUnion =
    groups.length === 0
      ? "never"
      : groups
          .flatMap((g) => [
            `\`_groupHover_${g.suffix}\``,
            `\`_groupFocus_${g.suffix}\``,
            `\`_groupFocusVisible_${g.suffix}\``,
            `\`_groupActive_${g.suffix}\``,
            `\`_groupDisabled_${g.suffix}\``,
          ])
          .join(" | ");

  const staticConditionUnion = STATIC_CONDITION_KEYS.map((c) => JSON.stringify(c)).join(" | ");

  const banner = options.banner ?? "// Auto-generated by @bearbones/codegen. Do not edit by hand.";

  return `${banner}

export type BearbonesUtilityName = ${utilityUnion};

export type BearbonesStaticConditionKey = ${staticConditionUnion};

export type BearbonesGroupConditionKey = ${groupConditionUnion};

export type BearbonesConditionKey =
  | BearbonesStaticConditionKey
  | BearbonesGroupConditionKey;

export type BearbonesConditionObject = {
  [K in BearbonesConditionKey]?:
    | BearbonesUtilityName
    | readonly BearbonesUtilityName[]
    | BearbonesConditionObject;
};

export type BearbonesStyleInput =
  | BearbonesUtilityName
  | BearbonesConditionObject
  | Record<string, unknown>
  | false
  | null
  | undefined;

export interface BearbonesGroup<Id extends string = string> {
  readonly anchor: string;
  readonly hover: \`_groupHover_\${Id}_\${string}\`;
  readonly focus: \`_groupFocus_\${Id}_\${string}\`;
  readonly active: \`_groupActive_\${Id}_\${string}\`;
  readonly focusVisible: \`_groupFocusVisible_\${Id}_\${string}\`;
  readonly disabled: \`_groupDisabled_\${Id}_\${string}\`;
}
`;
}
