packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  "@bramus/specificity": ^2.4.2
  "@pandacss/dev": ^1.10.0
  "@types/node": ^24
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@vitejs/plugin-react": ^6.0.1
  react: ^19.2.5
  react-dom: ^19.2.5
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: ^0.1.20
  vitest: npm:@voidzero-dev/vite-plus-test@latest

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
