/**
 * Public entry point for the `bearbones` package.
 *
 * The runtime surface here is intentionally minimal — Panda owns the heavy
 * lifting. We only ship:
 *
 *   - `cx`: a clsx-style class string joiner used to combine multiple class
 *     strings (the result of `css()`, recipe outputs, prop passthrough, etc.).
 *
 *   - Type-only re-exports: `BearbonesStyleInput`, `BearbonesGroup`, etc.
 *     Auto-generated by `@bearbones/codegen` and surfaced through this
 *     module's public types.
 *
 *   - Re-exports of `css`, `cva`, `sva` from the host project's
 *     `styled-system/` directory (Panda's generated runtime). At install time
 *     a tiny shim is wired up so `import { css } from 'bearbones'` resolves
 *     to the host's `styled-system/css`. See `wireUp()` below.
 *
 * Note on `css()` and friends: the actual runtime functions live in the host
 * project's `styled-system/` directory (Panda's codegen output). The bearbones
 * facade is a *type-erased* reference; the lowering transform in
 * `@bearbones/vite` rewrites `import { css } from 'bearbones'` → matching
 * Panda imports during the parser:before pass. (MVP simplification: this
 * rewrite is not yet implemented; consumers temporarily import `css` directly
 * from `styled-system/css`. Tracked in the design spec under "open questions:
 * facade rewriting.")
 *
 * The `cx` and `group` exports are full runtime implementations and ship from
 * this package without any rewriting.
 */

/**
 * clsx-style class string concat. Loose by design — accepts arbitrary strings
 * and falsy values. The discipline lives at the `css()` boundary, not here.
 */
export function cx(...args: Array<string | false | null | undefined>): string {
  let out = "";
  for (const arg of args) {
    if (!arg) continue;
    if (out.length === 0) {
      out = arg;
    } else {
      out = out + " " + arg;
    }
  }
  return out;
}

/**
 * Runtime shape returned from `group(...)` after the transform rewrites the
 * call site. Useful only as a TypeScript type — at runtime, the transform
 * replaces every `group('id')` call with a synthesized object literal.
 *
 * If a consumer somehow imports `group` directly without running through the
 * transform (e.g., an SSR runtime that didn't pre-build), this fallback
 * implementation returns a minimal record that throws on access. That's the
 * loudest possible signal that the build pipeline isn't wired correctly.
 */
export function group<Id extends string>(_id: Id): BearbonesGroupRuntime<Id> {
  throw new Error(
    "bearbones: group() was called at runtime. " +
      "This usually means the @bearbones/vite transform did not run before this module. " +
      "Verify Panda's hooks include bearbonesHooks() and that the file imports `group` from 'bearbones'.",
  );
}

export interface BearbonesGroupRuntime<Id extends string = string> {
  readonly anchor: string;
  readonly hover: `_groupHover_${Id}_${string}`;
  readonly focus: `_groupFocus_${Id}_${string}`;
  readonly active: `_groupActive_${Id}_${string}`;
  readonly focusVisible: `_groupFocusVisible_${Id}_${string}`;
  readonly disabled: `_groupDisabled_${Id}_${string}`;
}

/**
 * The closed union of every utility-string name accepted by `css()`.
 * Re-exported from `@bearbones/vite` where the source-of-truth scales live.
 *
 * Note: this is a static derivation of the MVP utility vocabulary. Once
 * `@bearbones/codegen` is fully wired up, this type will be regenerated
 * per-project from the resolved Panda preset, allowing teams to extend or
 * narrow the vocabulary via their own preset.
 */
export type { BearbonesUtilityName } from "@bearbones/vite";

/**
 * Anything `css()` accepts as a single argument. Conditional objects with
 * group symbols, Panda style objects, falsy values, and the `BearbonesGroup`
 * `.anchor` string also pass through without complaint.
 */
import type { BearbonesUtilityName } from "@bearbones/vite";

export type BearbonesConditionObject = {
  [conditionKey: string]:
    | BearbonesUtilityName
    | readonly BearbonesUtilityName[]
    | BearbonesConditionObject
    | Record<string, unknown>;
};

export type BearbonesStyleInput =
  | BearbonesUtilityName
  | BearbonesConditionObject
  | Record<string, unknown>
  | false
  | null
  | undefined;
