/**
 * Build-time helpers — separated from the runtime entry on `./` so that
 * Panda hooks bundled into a host project don't drag the rolldown plugin
 * + node fs glue into their bundle. Each plugin's `vite.config.ts` and
 * `scripts/generate-templates.mjs` import from `@klinking/panda-utils/build`.
 */

import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

export interface InlineTemplatesConfig {
  /** Absolute path to the directory holding the `.ts` template files. */
  templatesDir: string;
  /** Absolute path of the generated `templates.generated.ts` to (over)write. */
  outputPath: string;
}

/** Absolute paths of every template file currently on disk under `templatesDir`. */
export function listTemplateFiles(config: InlineTemplatesConfig): string[] {
  return readdirSync(config.templatesDir)
    .filter((name) => name.endsWith(".ts"))
    .sort()
    .map((name) => join(config.templatesDir, name));
}

function camelCase(name: string): string {
  return name.replace(/-([a-z])/g, (_, ch: string) => ch.toUpperCase());
}

function quoteAsTsTemplateLiteral(source: string): string {
  return source.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

/**
 * Read every template file in `templatesDir` and write a single
 * `templates.generated.ts` module that exports each body as a string
 * constant plus a `TEMPLATES` lookup record. Idempotent. Returns the list
 * of source paths read so callers can register them as watch dependencies.
 */
export function generateTemplates(config: InlineTemplatesConfig): string[] {
  const files = listTemplateFiles(config);

  const exportedConsts = files
    .map((path) => {
      const baseName = path.split("/").pop()!.replace(/\.ts$/, "");
      const constName = camelCase(baseName);
      const body = readFileSync(path, "utf8");
      return { baseName, constName, body };
    })
    .map(
      ({ baseName, constName, body }) =>
        `// Inlined from src/templates/${baseName}.ts\nexport const ${constName} = \`${quoteAsTsTemplateLiteral(body)}\`;\n`,
    )
    .join("\n");

  const lookupEntries = files
    .map((path) => {
      const baseName = path.split("/").pop()!.replace(/\.ts$/, "");
      const constName = camelCase(baseName);
      return `  ${JSON.stringify(baseName)}: ${constName},`;
    })
    .join("\n");

  const out = `// AUTO-GENERATED by @klinking/panda-utils — do not edit by hand.
// Source of truth: src/templates/*.ts in this package. Regenerated on each
// build via the inline-templates Vite plugin and on test setup via
// vitest globalSetup.

${exportedConsts}
export const TEMPLATES = {
${lookupEntries}
} as const;

export type TemplateName = keyof typeof TEMPLATES;
`;

  mkdirSync(dirname(config.outputPath), { recursive: true });
  writeFileSync(config.outputPath, out, "utf8");
  return files;
}

/**
 * Vite plugin that inlines `templatesDir/*.ts` into `outputPath` so the
 * bundle has no runtime fs reads or `import.meta.url` reliance. Each plugin
 * package consumes this in its `vite.config.ts`.
 *
 * Critical: regen runs ONLY when something actually demands it — on the
 * first build, and on `watchChange` for template source files. Regenerating
 * on every `buildStart` would write `templates.generated.ts` (which
 * `codegen-templates.ts` imports), and rolldown's import-graph watcher
 * would see that write as a change → fire another `buildStart` → regen
 * again → infinite loop. Gating regen with a `pendingGen` flag breaks the
 * cycle.
 */
export function inlineTemplatesPlugin(config: InlineTemplatesConfig): {
  name: string;
  buildStart(this: { addWatchFile(path: string): void }): void;
  watchChange(id: string): void;
} {
  const templateFiles = listTemplateFiles(config);
  let pendingGen = true;

  return {
    name: "klinking-panda:inline-templates",
    buildStart(this: { addWatchFile(path: string): void }) {
      if (pendingGen) {
        generateTemplates(config);
        pendingGen = false;
      }
      for (const file of templateFiles) {
        this.addWatchFile(file);
      }
    },
    watchChange(id: string) {
      if (templateFiles.includes(id)) {
        pendingGen = true;
      }
    },
  };
}
